name = "Best Modpack"
author = "chyzman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9942c00400a1db5f7e69438e07f9a2044919296bead2c473d40e0a2bba79f2d0"

[versions]
fabric = "0.18.0"
minecraft = "1.21.1"
